spring.application.name=wallet-service
spring.mvc.problemdetails.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5433/wallet_db
spring.datasource.username=wallet
spring.datasource.password=wallet

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

spring.flyway.enabled=true

server.port=8080